// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated from: abi_structs_schema.yaml
// Schema version: 1.0.0
// Generated at: 2026-01-30 17:37:10
// Schema hash: 019b094a389af9f3
// ============================================================================

package com.astraeus.native_api;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

/**
 * Auto-generated FFM MemoryLayout definitions for ABI structs.
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate using: java com.astraeus.tools.ABICodeGenerator
 */
public class StructLayouts {

    // Schema metadata
    public static final String SCHEMA_VERSION = "1.0.0";
    public static final String GENERATION_TIMESTAMP = "2026-01-30 17:37:10";
    public static final String SCHEMA_HASH = "019b094a389af9f3";

    // Frame statistics (exposed to Java)
    public static final StructLayout FRAMESTATS_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_LONG.withName("frame_number"),
        ValueLayout.JAVA_DOUBLE.withName("delta_time_ms"),
        ValueLayout.JAVA_DOUBLE.withName("render_time_ms"),
        ValueLayout.JAVA_INT.withName("draw_calls"),
        ValueLayout.JAVA_INT.withName("triangle_count"),
        ValueLayout.JAVA_INT.withName("entity_count"),
        MemoryLayout.sequenceLayout(4, ValueLayout.JAVA_BYTE).withName("_padding")
    );

    // VarHandles for FrameStats
    public static final VarHandle FRAMESTATS_FRAME_NUMBER = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("frame_number")
    );
    public static final VarHandle FRAMESTATS_DELTA_TIME_MS = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("delta_time_ms")
    );
    public static final VarHandle FRAMESTATS_RENDER_TIME_MS = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("render_time_ms")
    );
    public static final VarHandle FRAMESTATS_DRAW_CALLS = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("draw_calls")
    );
    public static final VarHandle FRAMESTATS_TRIANGLE_COUNT = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("triangle_count")
    );
    public static final VarHandle FRAMESTATS_ENTITY_COUNT = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("entity_count")
    );
    public static final VarHandle FRAMESTATS__PADDING = FRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("_padding"),
        MemoryLayout.PathElement.sequenceElement()
    );

    // Telemetry frame statistics (for telemetry system)
    public static final StructLayout TELEMETRYFRAMESTATS_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_LONG.withName("frame_number"),
        ValueLayout.JAVA_DOUBLE.withName("cpu_time_ms"),
        ValueLayout.JAVA_DOUBLE.withName("gpu_time_ms"),
        ValueLayout.JAVA_DOUBLE.withName("total_time_ms"),
        ValueLayout.JAVA_INT.withName("draw_calls"),
        ValueLayout.JAVA_INT.withName("triangle_count"),
        ValueLayout.JAVA_BYTE.withName("pass_count"),
        MemoryLayout.sequenceLayout(7, ValueLayout.JAVA_BYTE).withName("_padding")
    );

    // VarHandles for TelemetryFrameStats
    public static final VarHandle TELEMETRYFRAMESTATS_FRAME_NUMBER = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("frame_number")
    );
    public static final VarHandle TELEMETRYFRAMESTATS_CPU_TIME_MS = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("cpu_time_ms")
    );
    public static final VarHandle TELEMETRYFRAMESTATS_GPU_TIME_MS = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("gpu_time_ms")
    );
    public static final VarHandle TELEMETRYFRAMESTATS_TOTAL_TIME_MS = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("total_time_ms")
    );
    public static final VarHandle TELEMETRYFRAMESTATS_DRAW_CALLS = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("draw_calls")
    );
    public static final VarHandle TELEMETRYFRAMESTATS_TRIANGLE_COUNT = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("triangle_count")
    );
    public static final VarHandle TELEMETRYFRAMESTATS_PASS_COUNT = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("pass_count")
    );
    public static final VarHandle TELEMETRYFRAMESTATS__PADDING = TELEMETRYFRAMESTATS_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("_padding"),
        MemoryLayout.PathElement.sequenceElement()
    );

    // Viewport configuration
    public static final StructLayout VIEWPORTCONFIG_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_INT.withName("width"),
        ValueLayout.JAVA_INT.withName("height"),
        ValueLayout.JAVA_FLOAT.withName("aspect_ratio"),
        MemoryLayout.sequenceLayout(4, ValueLayout.JAVA_BYTE).withName("_padding")
    );

    // VarHandles for ViewportConfig
    public static final VarHandle VIEWPORTCONFIG_WIDTH = VIEWPORTCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("width")
    );
    public static final VarHandle VIEWPORTCONFIG_HEIGHT = VIEWPORTCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("height")
    );
    public static final VarHandle VIEWPORTCONFIG_ASPECT_RATIO = VIEWPORTCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("aspect_ratio")
    );
    public static final VarHandle VIEWPORTCONFIG__PADDING = VIEWPORTCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("_padding"),
        MemoryLayout.PathElement.sequenceElement()
    );

    // Multi-line description
    public static final StructLayout PIXELBUFFERVIEW_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.ADDRESS.withName("data"),
        ValueLayout.JAVA_INT.withName("width"),
        ValueLayout.JAVA_INT.withName("height"),
        ValueLayout.JAVA_INT.withName("stride"),
        ValueLayout.JAVA_INT.withName("format"),
        ValueLayout.JAVA_INT.withName("max_backing_width"),
        ValueLayout.JAVA_INT.withName("max_backing_height"),
        ValueLayout.JAVA_INT.withName("max_backing_size")
    );

    // VarHandles for PixelBufferView
    public static final VarHandle PIXELBUFFERVIEW_DATA = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("data")
    );
    public static final VarHandle PIXELBUFFERVIEW_WIDTH = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("width")
    );
    public static final VarHandle PIXELBUFFERVIEW_HEIGHT = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("height")
    );
    public static final VarHandle PIXELBUFFERVIEW_STRIDE = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("stride")
    );
    public static final VarHandle PIXELBUFFERVIEW_FORMAT = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("format")
    );
    public static final VarHandle PIXELBUFFERVIEW_MAX_BACKING_WIDTH = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("max_backing_width")
    );
    public static final VarHandle PIXELBUFFERVIEW_MAX_BACKING_HEIGHT = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("max_backing_height")
    );
    public static final VarHandle PIXELBUFFERVIEW_MAX_BACKING_SIZE = PIXELBUFFERVIEW_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("max_backing_size")
    );

    // Configuration for readback buffers
    public static final StructLayout READBACKCONFIG_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_INT.withName("max_width"),
        ValueLayout.JAVA_INT.withName("max_height"),
        ValueLayout.JAVA_INT.withName("format"),
        ValueLayout.JAVA_BOOLEAN.withName("enable_double_buffer")
    );

    // VarHandles for ReadbackConfig
    public static final VarHandle READBACKCONFIG_MAX_WIDTH = READBACKCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("max_width")
    );
    public static final VarHandle READBACKCONFIG_MAX_HEIGHT = READBACKCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("max_height")
    );
    public static final VarHandle READBACKCONFIG_FORMAT = READBACKCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("format")
    );
    public static final VarHandle READBACKCONFIG_ENABLE_DOUBLE_BUFFER = READBACKCONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("enable_double_buffer")
    );

    // Picking result
    public static final StructLayout PICKRESULT_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_INT.withName("entity_id"),
        ValueLayout.JAVA_FLOAT.withName("depth"),
        ValueLayout.JAVA_FLOAT.withName("world_x"),
        ValueLayout.JAVA_FLOAT.withName("world_y"),
        ValueLayout.JAVA_FLOAT.withName("world_z"),
        ValueLayout.JAVA_BOOLEAN.withName("hit"),
        MemoryLayout.sequenceLayout(3, ValueLayout.JAVA_BYTE).withName("_padding")
    );

    // VarHandles for PickResult
    public static final VarHandle PICKRESULT_ENTITY_ID = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("entity_id")
    );
    public static final VarHandle PICKRESULT_DEPTH = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("depth")
    );
    public static final VarHandle PICKRESULT_WORLD_X = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("world_x")
    );
    public static final VarHandle PICKRESULT_WORLD_Y = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("world_y")
    );
    public static final VarHandle PICKRESULT_WORLD_Z = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("world_z")
    );
    public static final VarHandle PICKRESULT_HIT = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("hit")
    );
    public static final VarHandle PICKRESULT__PADDING = PICKRESULT_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("_padding"),
        MemoryLayout.PathElement.sequenceElement()
    );

    // Engine configuration
    public static final StructLayout ENGINECONFIG_LAYOUT = MemoryLayout.structLayout(
        ValueLayout.JAVA_INT.withName("initial_width"),
        ValueLayout.JAVA_INT.withName("initial_height"),
        ValueLayout.JAVA_BOOLEAN.withName("enable_validation"),
        ValueLayout.JAVA_BOOLEAN.withName("enable_debug_output"),
        ValueLayout.ADDRESS.withName("log_file_path")
    );

    // VarHandles for EngineConfig
    public static final VarHandle ENGINECONFIG_INITIAL_WIDTH = ENGINECONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("initial_width")
    );
    public static final VarHandle ENGINECONFIG_INITIAL_HEIGHT = ENGINECONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("initial_height")
    );
    public static final VarHandle ENGINECONFIG_ENABLE_VALIDATION = ENGINECONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("enable_validation")
    );
    public static final VarHandle ENGINECONFIG_ENABLE_DEBUG_OUTPUT = ENGINECONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("enable_debug_output")
    );
    public static final VarHandle ENGINECONFIG_LOG_FILE_PATH = ENGINECONFIG_LAYOUT.varHandle(
        MemoryLayout.PathElement.groupElement("log_file_path")
    );

}
